name: Code Scan

on:
  workflow_call:
    inputs:
      codeScanFileName:
        required: true
        type: string
        default: "codeScan"

      uploadPath:
        required: true
        type: string

      CONTAINER_NAME:
        required: true
        type: string
        default: "codeScan"

# env:
#   codeScanFileName: "codeScan"
#   uploadPath: ""
#   CONTAINER_NAME: "codeScan"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:20-git

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: VincyZhang/intel-extension-for-transformers/.github/workflows/docker-template.yml@xuehao/itrex_ci
        with:
          DOCKER_CONFIG_NAME: "commonDockerConfig"
          REPO_NAME: "code-scan"
          REPO_TAG: "1.0"
          DOCKER_FILE_NAME: "DockerfileCodeScan"
          CONTAINER_NAME: ${{ env.codeScanContainerName }}

      - name: Docker clean up
        run: |
          docker ps -a
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm -vf ${{ env.CONTAINER_NAME }} || true

      - name: Code scan check
        run: |
          docker run -v ${{ github.workspace }}:/intel-extension-for-transformers -it --rm \
              --name ${{ env.CONTAINER_NAME }} code-scan:1.0 \
              /intel-extension-for-transformers/.github/workflows/script/formatScan/${{ env.codeScanFileName }}.sh

      - name: Publish pipeline artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.codeScanFileName }}
          path: .github/workflows/script/formatScan/${{ env.uploadPath }}

      - name: Docker clean up
        run: |
          docker exec ${{ env.CONTAINER_NAME }} bash -c "rm -fr /intel-extension-for-transformers/* && rm -fr /intel-extension-for-transformers/.* || true"
