name: Code Scan

on:
  workflow_call:
    inputs:
      codeScanFileName:
        required: true
        type: string
        default: "codeScan"

      uploadPath:
        required: true
        type: string

      CONTAINER_NAME:
        type: string
        default: "codeScan"

# env:
#   codeScanFileName: "codeScan"
#   uploadPath: ""
#   CONTAINER_NAME: "codeScan"

jobs:
  set_up_docker:
    uses: VincyZhang/intel-extension-for-transformers/.github/workflows/docker-template.yml@xuehao/itrex_ci
    with:
      DOCKER_CONFIG_NAME: "commonDockerConfig"
      REPO_NAME: "code-scan"
      REPO_TAG: "1.0"
      DOCKER_FILE_NAME: "DockerfileCodeScan"
      CONTAINER_NAME: ${{ inputs.CONTAINER_NAME }}

  build:
    needs: set_up_docker
    steps:
      - name: Code scan check
        run: |
          docker run -v ${{ github.workspace }}:/intel-extension-for-transformers -it --rm \
              --name ${{ inputs.CONTAINER_NAME }} code-scan:1.0 \
              /intel-extension-for-transformers/.github/workflows/script/formatScan/${{ inputs.codeScanFileName }}.sh

      - name: Publish pipeline artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.codeScanFileName }}
          path: .github/workflows/script/formatScan/${{ inputs.uploadPath }}

      - name: Docker clean up
        run: |
          docker exec ${{ inputs.CONTAINER_NAME }} bash -c "rm -fr /intel-extension-for-transformers/* && rm -fr /intel-extension-for-transformers/.* || true"
