name: Code Scan

on:
  workflow_call:
    inputs:
      codeScanFileName:
        required: true
        type: string
        default: "codeScan"

      uploadPath:
        required: true
        type: string

      CONTAINER_NAME:
        type: string
        default: "codeScan"

# env:
#   codeScanFileName: "codeScan"
#   uploadPath: ""
#   CONTAINER_NAME: "codeScan"

env:
  DOCKER_CONFIG_NAME: "commonDockerConfig"
  REPO_NAME: "code-scan"
  REPO_TAG: "1.0"
  DOCKER_FILE_NAME: "codeScan"

jobs:
  # set_up_docker:
  #   uses: VincyZhang/intel-extension-for-transformers/.github/workflows/docker-template.yml@xuehao/itrex_ci
  #   with:
  #     DOCKER_CONFIG_NAME: "commonDockerConfig"
  #     REPO_NAME: "code-scan"
  #     REPO_TAG: "1.0"
  #     DOCKER_FILE_NAME: "codeScan"
  #     CONTAINER_NAME: ${{ inputs.CONTAINER_NAME }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: ["pylint"]
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -f ${{ github.workspace }}/.github/workflows/docker/${{ env.DOCKER_FILE_NAME }}.dockerfile -t ${{ env.REPO_NAME }}:${{ env.REPO_TAG }} .

      - name: Docker Run
        run: |
          docker run -dit --disable-content-trust --privileged --name=${{ inputs.CONTAINER_NAME }} --shm-size="2g" \
          -v ${{ github.workspace }}:/intel-extension-for-transformers \
          ${{ parameters.repoName }}:${{ parameters.repoTag }}

      - name: Code scan check
        run: |
          docker exec ${{ inputs.CONTAINER_NAME }} \
          bash /intel-extension-for-transformers/.github/workflows/script/formatScan/${{ matrix.job_name }}.sh

      - name: Publish pipeline artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.job_name }}
          path: .github/workflows/script/formatScan/${{ inputs.uploadPath }}

      - name: Docker clean up
        run: |
          docker exec ${{ inputs.CONTAINER_NAME }} bash -c "rm -fr /intel-extension-for-transformers/* && rm -fr /intel-extension-for-transformers/.* || true"
