name: Code Scan

on:
  workflow_call:
    inputs:
      codeScanFileName:
        required: true
        type: string
        default: "codeScan"

      uploadPath:
        required: true
        type: string

      CONTAINER_NAME:
        type: string
        default: "codeScan"

# env:
#   codeScanFileName: "codeScan"
#   uploadPath: ""
#   CONTAINER_NAME: "codeScan"

jobs:
  # set_up_docker:
  #   uses: VincyZhang/intel-extension-for-transformers/.github/workflows/docker-template.yml@xuehao/itrex_ci
  #   with:
  #     DOCKER_CONFIG_NAME: "commonDockerConfig"
  #     REPO_NAME: "code-scan"
  #     REPO_TAG: "1.0"
  #     DOCKER_FILE_NAME: "codeScan"
  #     CONTAINER_NAME: ${{ inputs.CONTAINER_NAME }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out Repo
        if: inputs.DOCKER_CONFIG_NAME == 'commonDockerConfig'
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ github.workspace }}/.github/workflows/docker/${{ inputs.DOCKER_FILE_NAME }}.dockerfile
          tags: ${{ inputs.REPO_NAME }}\:${{ inputs.REPO_TAG }}
          outputs: type=docker,dest=/tmp/docker_image.tar

      - name: Code scan check
        run: |
          docker run -v ${{ github.workspace }}:/intel-extension-for-transformers -i --rm \
              --name ${{ inputs.CONTAINER_NAME }} code-scan:1.0 \
              /intel-extension-for-transformers/.github/workflows/script/formatScan/${{ inputs.codeScanFileName }}.sh

      - name: Publish pipeline artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.codeScanFileName }}
          path: .github/workflows/script/formatScan/${{ inputs.uploadPath }}

      - name: Docker clean up
        run: |
          docker exec ${{ inputs.CONTAINER_NAME }} bash -c "rm -fr /intel-extension-for-transformers/* && rm -fr /intel-extension-for-transformers/.* || true"
