name: Code Scan

on:
  workflow_call:
    inputs:
      codeScanFileName:
        required: true
        type: string
        default: "codeScan"

      uploadPath:
        required: true
        type: string

      CONTAINER_NAME:
        type: string
        default: "codeScan"

env:
  DOCKER_CONFIG_NAME: "commonDockerConfig"
  REPO_NAME: "code-scan"
  REPO_TAG: "1.0"
  DOCKER_FILE_NAME: "codeScan"

jobs:
  format-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: ["pylint", "bandit", "clangformat", "cloc", "cpplint", "pydocstyle", "pyspelling"]
      fail-fast: false
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -f ${{ github.workspace }}/.github/workflows/docker/${{ env.DOCKER_FILE_NAME }}.dockerfile -t ${{ env.REPO_NAME }}:${{ env.REPO_TAG }} .

      - name: Docker Run
        run: |
          docker run -dit --disable-content-trust --privileged --name=${{ inputs.CONTAINER_NAME }} --shm-size="2g" \
          -v ${{ github.workspace }}:/intel-extension-for-transformers \
          ${{ env.REPO_NAME }}:${{ env.REPO_TAG }}
      
      - name: Env build
        run: |
          docker exec ${{ inputs.CONTAINER_NAME }} \
          bash /intel-extension-for-transformers/.github/workflows/script/prepare_env.sh

      - name: Code scan check
        run: |
          docker exec ${{ inputs.CONTAINER_NAME }} \
          bash /intel-extension-for-transformers/.github/workflows/script/formatScan/${{ matrix.job_name }}.sh

      - name: Publish pipeline artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.job_name }}
          path: ${{ github.workspace }}/.github/workflows/script/formatScan/${{ matrix.job_name }}.*

      - name: Docker clean up
        run: |
          docker exec ${{ inputs.CONTAINER_NAME }} bash -c "rm -fr /intel-extension-for-transformers/* && rm -fr /intel-extension-for-transformers/.* || true"
