name: DocStyle Code Scan

on:
  pull_request:
    branches: [main]
    paths:
      - intel_extension_for_transformers
      - setup.py
      - .github/workflows/format_scan.yml
      - .github/workflows/script/formatScan
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-scan:
    uses: ./.github/workflows/code-scan-template.yml
    with:
      codeScanFileName: pylint
      uploadPath: "pylint.json"
