name: DocStyle Code Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [main]
    paths:
      - intel_extension_for_transformers
      - setup.py
      - .github/workflows/format_scan.yml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job runs the pydocstyle code scan
  DocStyle:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run pylint code scan
        uses: code-scan-template.yml
        with:
          codeScanFileName: "pylint"
          uploadPath: "pylint.json"

      # - run: |
      #     python -m pip install pylint==2.12.1
      #     python -m pip install --default-timeout=100 -r requirements.txt
      #     python -m pip install intel-extension-for-transformers
      #     python -m pip list
      #     python -m pylint -f json --disable=R,C,W,E1129 \
      #         --enable=line-too-long \
      #         --max-line-length=120 \
      #         --extension-pkg-whitelist=numpy \
      #         --ignored-classes=TensorProto,NodeProto \
      #         --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime,neural_compressor,engine_py,neural_engine_py \
      #         ${GITHUB_WORKSPACE}/intel_extension_for_transformers
