on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo comment on issue $NUMBER
          echo comment ${{ github.event.issue.body }}
          echo assignee ${{ github.event.issue.assignees }}
          echo issue id ${{ github.event.issue.id }}
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ vars.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/VincyZhang/intel-extension-for-transformers/issues/comments/${{ github.event.issue.number }} \
            -d '{"body":"If you need help, please @NeuralChatBot"}'
        env:
          NUMBER: ${{ github.event.issue.number }}