name: Auto Label
on: workflow_dispatch

jobs:
  Issue_label:
    name: Issue label
    runs-on: issues-node
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v3
      - name: Comment on Issue
        run: |
          echo label on issue $NUMBER
          python ${{ github.workspace }}/.github/workflows/script/ask_neuralchat.py --stage "label" --label "${{ github.event.label.name }}"
        env:
          NUMBER: ${{ github.event.issue.number }}
          TOKEN: ${{ vars.TOKEN }}
          COMMEND_ID: ${{ github.event.comment.id }}
          no_proxy: "intel.com,.intel.com,localhost,127.0.0.1"
          maintain_list: ${{ vars.developer_list }}
          NEURALCHAT_SERVER: ${{ vars.NEURALCHAT_SERVER }}