on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/VincyZhang/intel-extension-for-transformers/issues/4/comments \
            -d '{"body":"If you need help, please @NeuralChatBot"}'
        env:
          NUMBER: ${{ github.event.issue.number }}