name: Auto Label
on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: issues-node
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v3

      - name: Comment on Issue
        run: |
          echo comment on issue $NUMBER
          user=${{ github.event.comment.user.login }}
          comment_content="${{ github.event.comment.body }}"
          if [[ ${comment_content} == *"If you need help, please @NeuralChatBot" ]] || [[ ${user} == "NeuralChatBot" ]]; then
          echo "This is a message from NeuralChatBot or Our Developers, IGNORE!"
          elif [[ ${comment_content} == *"@NeuralChatBot label"* ]] && [[ ${user} != "NeuralChatBot" ]]; then
            labels=$(echo -e ${comment_content} | grep -o "@NeuralChatBot label.*" | awk -F "labels" '{print $2}')
            [[ -z ${labels} ]] && labels=$(echo -e ${comment_content} | grep -o "@NeuralChatBot label.*" | awk -F "label" '{print $2}')
            echo "Label Issue $NUMBER with ${labels} As User Requied"
            python ${{ github.workspace }}/.github/workflows/script/auto_label.py --labels "${labels}"
          else
            echo "Request NeuralChatBot for Labels"
            #python ${{ github.workspace }}/.github/workflows/script/auto_label.py
          fi
        env:
          NUMBER: ${{ github.event.issue.number }}
          TOKEN: ${{ vars.TOKEN }}