name: Trigger NeuralChat BOT
on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: issues-node
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v3
      
      - name: Comment on Issue
        run: |
          echo comment on issue $NUMBER
          comment_content="${{ github.event.comment.body }}"
          if [[ ${comment_content} == "If you need help, please @NeuralChatBot" ]]; then
            echo "ignore instructions"
          elif [[ ${comment_content} == *"@NeuralChatBot"* ]]; then
            echo ask for neuralchat ${issue_content}
            python ${{ github.workspace }}/.github/workflows/script/connect_neuralchat.py --stage "comment"
          fi
        env:
          NUMBER: ${{ github.event.issue.number }}
          TOKEN: ${{ vars.TOKEN }}