name: Trigger NeuralChat BOT
on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: issues-node
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v3

      - name: Comment on Issue
        run: |
          echo comment on issue $NUMBER
          user=${{ github.event.comment.user.login }}
          if [[ ${user} == "NeuralChatBot" ]]; then
            echo "This is a message from NeuralChatBot or Our Developers, IGNORE!"
          else
            echo "Reqeust NeuralChatBot for issue $NUMBER from $user"
            python ${{ github.workspace }}/.github/workflows/script/ask_neuralchat.py --stage "update"
          fi
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMEND_ID: ${{ github.event.comment.id }}
          TOKEN: ${{ vars.TOKEN }}
          no_proxy: "intel.com,.intel.com,localhost,127.0.0.1"
          maintain_list: ${{ vars.developer_list }}
          NEURALCHAT_SERVER: ${{ vars.NEURALCHAT_SERVER }}