name: Reply Instructions
on:
    issues:
      types: [opened, reopened]

jobs:
  issue_created:
    # This job only runs for issue comments
    name: Issue Create
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo comment on issue $NUMBER
          echo issue ${{ github.event.issue.body }}
          echo assignee ${{ github.event.issue.assignees }}
          echo issue id ${{ github.event.issue.id }}
          issue_content="${{ github.event.issue.body }}"
          if [[ ! $(echo ${issue_content} | grep "@NeuralChatBot") ]]; then
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ vars.TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/VincyZhang/intel-extension-for-transformers/issues/${{ github.event.issue.number }}/comments \
              -d '{"body":"If you need help, please @NeuralChatBot"}'
          fi

        env:
          NUMBER: ${{ github.event.issue.number }}