name: Reply Instructions
on:
    issues:
      types: [opened, reopened]

jobs:
  issue_created:
    # This job only runs for issue comments
    name: Issue Create
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo create issue $NUMBER
          python ./script/connect_neuralchat.py --stage "create"

        env:
          NUMBER: ${{ github.event.issue.number }}
          TOKEN: ${{ vars.TOKEN }}